# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$gcloud\
$aws\
$line_break\
$character"""

right_format = """
$python\
$golang\
$rust\
$cmd_duration\
$time"""

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[username]
show_always = true
format = "[$user]($style)@"
style_user = "bold text"

[hostname]
ssh_only = false
format = "[$hostname]($style)"
style = "bold flamingo"

[directory]
format = "[  $path ]($style)"
style = "italic lavender"

[git_branch]
format = " [$branch]($style) "
style = "italic mauve"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[🍒 PICKING](bold red)'

[gcloud]
format = '[󰅟 $account(@$domain)(\($region\))]($style) '
style = "bold yellow"

[aws]
format = '[󰅟 ($profile )(\($region\) )(\[$duration\] )]($style)'
style = "bold yellow"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[rust]
format = "[ ($version)]($style)"
style = "bright-green"

[python]
format = "[ ($version)]($style)"
style = "bright-green"

[golang]
format = "[ ($version)]($style)"
style = "bright-green"

[cmd_duration]
min_time = 0
format = "[ $duration]($style) "
style = "italic yellow"

[time]
disabled = false
format = "[$time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "italic dimmed white"
